# Generated by Django 4.1 on 2022-10-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("description", models.TextField(verbose_name="")),
            ],
            options={
                "verbose_name": "Руководство пользователя",
                "verbose_name_plural": "Руководства пользователей",
            },
        ),
    ]
