# Generated by Django 4.0.6 on 2022-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_tag_tag_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='news',
        ),
        migrations.AddField(
            model_name='tag',
            name='news',
            field=models.ManyToManyField(null=True, to='news.news'),
        ),
    ]
