# Generated by Django 4.0.6 on 2022-07-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='news',
        ),
    ]
