# Generated by Django 4.0.6 on 2022-07-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер аудитории')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.CharField(default='Главный корпус', max_length=100, verbose_name='Корпус')),
                ('address', models.CharField(default='Дубининская улица, дом 25', max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('abbriviation', models.CharField(max_length=100, verbose_name='Аббривеатура')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='LessonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пары')),
            ],
            options={
                'verbose_name': 'Название пары',
                'verbose_name_plural': 'Названия пар',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Лекция', max_length=100, verbose_name='Тип занятия')),
            ],
            options={
                'verbose_name': 'Тип занятия',
                'verbose_name_plural': 'Типы занятий',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(verbose_name='с:')),
                ('time_to', models.TimeField(verbose_name='до:')),
            ],
            options={
                'verbose_name': 'Время с-до',
                'verbose_name_plural': 'Времена с-до',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auditory', verbose_name='Аудитория')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building', verbose_name='Здание')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='Название пары')),
                ('even_week', models.BooleanField(verbose_name='Четная/нечетная неделя')),
                ('day', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='день недели')),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auditory', verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group', verbose_name='Группа')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessontype', verbose_name='Тип занятия')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor', verbose_name='Преподаватель')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timetable', verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialization', verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='auditory',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building', verbose_name='Здание'),
        ),
    ]
