# Generated by Django 4.1 on 2022-08-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('corp', models.CharField(default='Главное здание', max_length=64)),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default=('Понедельник', 'Понедельник'), max_length=30)),
            ],
            options={
                'verbose_name': 'день',
                'verbose_name_plural': 'дни',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation_on_ru', models.CharField(max_length=5, unique=True, verbose_name='Аббревиатура на русском')),
                ('abbreviation_on_eng', models.CharField(max_length=5, unique=True, verbose_name='Аббревиатура на английском')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=1, max_length=30, unique=True, verbose_name='название пары')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.building', verbose_name='Корпус')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.day', verbose_name='день недели')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='2022', max_length=30, unique=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Расписание на год',
                'verbose_name_plural': 'Расписания на года',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=1, unique=True, verbose_name='Номер недели')),
                ('is_even', models.BooleanField(default=False, verbose_name='Четная/нечетная')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.year', to_field='date', verbose_name='год')),
            ],
            options={
                'verbose_name': 'Неделя',
                'verbose_name_plural': 'Недели',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(verbose_name='Время начала')),
                ('time_to', models.TimeField(verbose_name='Время окончания')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Время пары',
                'verbose_name_plural': 'Времена пар',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=32, null=True, verbose_name='фамилия')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='имя')),
                ('patronym', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.professor', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.week', verbose_name='неделя'),
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.professor', verbose_name='Куратор'),
        ),
    ]
