# Generated by Django 4.1 on 2022-09-14 11:05

from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=128, verbose_name="Адрес")),
                ("corp", models.CharField(default="Главное здание", max_length=64)),
            ],
            options={
                "verbose_name": "Корпус",
                "verbose_name_plural": "Корпуса",
            },
        ),
        migrations.CreateModel(
            name="ScheduleElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=128, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "starting_time",
                    models.TimeField(
                        default="", editable=False, verbose_name="Время начала"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        default="2022",
                        max_length=30,
                        unique=True,
                        verbose_name="Заголовок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание на год",
                "verbose_name_plural": "Расписания на года",
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.IntegerField(
                        default=1, unique=True, verbose_name="Номер недели"
                    ),
                ),
                (
                    "is_even",
                    models.BooleanField(default=False, verbose_name="Четная/нечетная"),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.year",
                        to_field="date",
                        verbose_name="год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Неделя",
                "verbose_name_plural": "Недели",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="фамилия"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="имя"
                    ),
                ),
                (
                    "patronym",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Отчество"
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbreviation_on_ru",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        verbose_name="Аббревиатура на русском",
                    ),
                ),
                (
                    "abbreviation_on_eng",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        verbose_name="Аббревиатура на английском",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.professor",
                        verbose_name="Куратор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=256,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                ("time", models.TimeField(default="00:00", verbose_name="Начало")),
                (
                    "date",
                    models.DateField(
                        default="<built-in method today of type object at 0x00007FFFF3580960>",
                        verbose_name="Дата",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        default="", max_length=128, verbose_name="Организатор"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "yandex_maps_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на яндекс карты"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="schedule.tag", verbose_name="Тэги"),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_day",
                    models.CharField(
                        choices=[
                            ("Понедельник", "Понедельник"),
                            ("Вторник", "Вторник"),
                            ("Среда", "Среда"),
                            ("Четверг", "Четверг"),
                            ("Пятница", "Пятница"),
                            ("Суббота", "Суббота"),
                            ("Воскресенье", "Воскресенье"),
                        ],
                        default=("Понедельник", "Понедельник"),
                        max_length=30,
                    ),
                ),
                (
                    "week",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.week",
                        verbose_name="Неделя",
                    ),
                ),
            ],
            options={
                "verbose_name": "день",
                "verbose_name_plural": "дни",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "scheduleelement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="schedule.scheduleelement",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        default=("1", "1"),
                        max_length=32,
                        unique=True,
                        verbose_name="Номер пары",
                    ),
                ),
                ("room", models.CharField(max_length=5, verbose_name="Кабинет")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.building",
                        verbose_name="Корпус",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.day",
                        verbose_name="День",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.group",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.professor",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            bases=("schedule.scheduleelement",),
        ),
    ]
