# Generated by Django 4.1 on 2022-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='event',
            name='yandex_maps_url',
            field=models.URLField(null=True, verbose_name='Ссылка на яндекс карты'),
        ),
    ]
