# Generated by Django 4.1 on 2022-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="week",
            name="title",
            field=models.IntegerField(default=1, verbose_name="Номер недели"),
        ),
    ]
