# Generated by Django 4.1 on 2022-09-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_event_date_alter_week_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.week",
                verbose_name="Неделя",
            ),
        ),
    ]
